source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'JVNSFetchedResultsControllerTableView_Tests' do
  pod 'JVNSFetchedResultsControllerTableView', :path => '../'
  
  
end
